/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        var teclado = new Scanner(System.in);

        Queue<String> q = new ArrayDeque<>();

        System.out.print("n: ");
        int n = teclado.nextInt();
        teclado.nextLine();
        String primeiro = "1";
        q.add(primeiro);

        for(int i = 0; i < n; i++){
            String valorFila = q.remove();
            String primeiroValor = valorFila + "0";
            String segundoValor = valorFila + "1";
            q.add(primeiroValor);
            q.add(segundoValor);
            System.out.println(valorFila);
        }
    }
}
