/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.net.http.HttpResponse;

public class App {
    public static void main(String[] args) {
        HttpResponse<String> response = Cliente.envia("https://api.adviceslip.com/advice");
        JsonObject jsonObject = new JsonParser().parseString(response.body()).getAsJsonObject();
        System.out.printf("Um concelho para a vida: %s\n", (jsonObject.get("slip")).getAsJsonObject().get("advice").getAsString());
    }
}
