/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Stack;

public class Pilha {

    public static void main(String[] args) {
        //TODO MEU JEITO DE FAZER A PILHA QUE O PROFESSOR PEDIU
//        try {
//            ArrayList lista = new ArrayList();
//            File entrada = new File("arquivo.txt");
//            Scanner linha = new Scanner(entrada);
//            int c = 0;
//            while (linha.hasNext()) {
//                lista.add(linha.nextLine());
//            }
//            for (int i = lista.size() - 1; i > 0; i--) {
//                System.out.println(lista.get(i));
//            }
//            linha.close();
//        } catch (FileNotFoundException e) {
//            System.err.println("Erro ao abrir arquivo");
//            e.printStackTrace();
//        }


        //TODO UTILIZANDO A API COLLECTION PARA FAZER

        Stack<String> stack = new Stack();
        try{
            File entrada = new File("arquivo.txt");
            Scanner linha = new Scanner(entrada);
            while (linha.hasNext()) {
                stack.push(linha.nextLine());
            }
            while(!stack.isEmpty()){
                System.out.println(stack.pop());
            }
        }catch (FileNotFoundException e) {
            System.err.println("Erro ao abrir arquivo");
            e.printStackTrace();
        }

    }
}
