/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.esd;

import ads.esd.exercicios_listasequencial.Exercicio01;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Exercicio01 classUnderTest = new Exercicio01();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
