/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.esd;

import ads.esd.estruturas.Pilha;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Exercicio01 {
    public static void main(String[] args)  {
        try{
            FileInputStream file = new FileInputStream("exercicio01.txt");
            Scanner scanner = new Scanner(file);
            Pilha pilha = new Pilha();

            while (scanner.hasNextLine()) {
                String linha = scanner.nextLine();
                String[] registro = linha.split(" ");
                if (!Character.isUpperCase(registro[0].charAt(0))) {
                    if (pilha.estaVazia()){
                        pilha.empilha(linha);
                    }else{
                        System.out.println(linha);
                        System.out.println(pilha.desempilha());
                    }
                } else {
                    System.out.println(linha);
                }

            }

        }catch (FileNotFoundException e){
            System.out.println("ARQUIVO INVALIDO");
        }
    }
}
