/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {

    public static void main(String[] args) {
        Dimensao dimen = new Dimensao(23.4, 33.1, 9);
        Telefone tel = new Telefone(2312,"113213", dimen, 1, "+QW5");
        Telefone telSem = new SemFio(2132, "333333", new Dimensao(1,3,2), 2, "+SW4", 2.4, 15, 50);

        System.out.println(tel.imprimirDados());
        System.out.println(telSem.imprimirDados());
    }
}
