/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
//    public static String formata(String m, String v) throws ParseException {
//        if (m == null || v == null) {
//            throw new IllegalArgumentException("Máscara e valor não podem ser nulos");
//        }
//        String resultado = "";
//        MaskFormatter mask = new MaskFormatter(m);
//        mask.setValueContainsLiteralCharacters(false);
//        mask.setPlaceholderCharacter('_');
//        resultado = mask.valueToString(v);
//        return resultado;
//    }

    public static void main(String[] args) {
//        Scanner ler  = new Scanner(System.in);
//        int a, b;
//
//        try{
//            System.out.print("Entre com o número: ");
//            a = ler.nextInt();
//            System.out.print("Entre com o número: ");
//            b = ler.nextInt();
//
//            double res = (double) a  / b;
//
//            System.out.println(a + " dividido por " + b + " = " + res);
//        }catch(InputMismatchException e){
//            System.err.println("Só é permitido números inteiros");
//            ler.nextLine();
//        }catch (ArithmeticException e){
//            System.err.println("Não é permitido dividir dois inteiros por zero");
//            ler.nextLine();
//        }catch (Exception e){
//            System.err.println("Um erro não identificado apareceu");
//            ler.nextLine();
//        }
//        System.out.println("Fim do programa");



//
//            try {
//                System.out.println(formata(null, "48998765432"));
//            } catch (ParseException e) {
//                System.err.println("Erro ao formatar a String");
//            } catch (IllegalArgumentException e) {
//                System.err.println("Erro: " + e.getMessage());
//            }

            
    }
}
