# docker-compose.yml -- webapp

services:
  webapp: 
    build: servidorweb
    ports:
      - 8000:8000
  bancodedados:
    image: mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
