/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Personagem p = new Aldeao(23, 2.2, 14);


        System.out.println(((Aldeao) p).coletar());
        System.out.println(((Aldeao) p).correr());
    }
}
