/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        System.out.println("Digite o comando: ");

        String comandoCompleto = teclado.nextLine();
        String[] comando = comandoCompleto.split(" ");

        Path currentDir =  Path.of(System.getProperty("user.dir"));

        //while(!comando[0].equals("exit")){
            switch (comando[0]) {
                case "ls" -> System.out.println("listando conteúdos");

                case "stat" -> {
                    String arquivo = comando[1];
                    System.out.println("imprimindo propriedades do arquivo " + arquivo);
                }

                case "mkfile" -> {
                    String arquivo = comando[1];
                    try{
                        Path arq = currentDir.resolve(arquivo);
                        Files.createFile(arq);
                    }catch(Exception e){
                        System.err.println("Erro: " + e);
                    }
                }
                case "rm" -> {
                    String arquivo = comando[1];
                    System.out.println("apagando o arquivo " + arquivo);
                }
                case "mv" -> {
                    String arquivo1 = comando[1];
                    String arquivo2 = comando[2];

                    System.out.println("renomeando o arquivo " + arquivo1 + " para " + arquivo2);
                }
                case "exit" -> System.out.println("Saindo...");
            }
        //}
    }
}
