/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        //TODO FAZER O RESTO DAS FUNCIONALIDADES

        Scanner teclado = new Scanner(System.in);

        ArrayList<Veiculo> garagem = new ArrayList<>();

        garagem.add(new Ferrari(1));
        garagem.add(new Pampa(2));
        garagem.add(new Panther(3, 50));

        for (Veiculo veiculo : garagem) {
            veiculo.acelerar(50);
            veiculo.frear(30);
        }


        // Usando polimorfismo na instrução abaixo
        for (Veiculo veiculo : garagem) {
            if (veiculo instanceof Ferrari) {
                Ferrari ferrari = (Ferrari) veiculo;
                boolean situacaoFarol = ferrari.ligarDesligarFarol();

                if (situacaoFarol) {
                    System.out.println("Farol ligado com sucesso!");
                }else{
                    System.out.println("Farol desligado com sucesso!");
                }
                System.out.println();

            } else if (veiculo instanceof Pampa) {
                Pampa pampa = (Pampa) veiculo;

                boolean situacaoTracao = pampa.ativarDesativarTracao();
                if (situacaoTracao) {
                    System.out.println("Tração foi ativada com sucesso!");
                }else {
                    System.out.println("Tração foi desativada com sucesso!");
                }
                System.out.println();

            } else if (veiculo instanceof Panther) {
                Panther panther = (Panther) veiculo;

                //controlar situação das rodas
                boolean situacaoRodas =  panther.abrirRecolherRodas();
                if(situacaoRodas){
                    System.out.println("Rodas recolhidas com sucesso!");
                }else{
                    System.out.println("Rodas realocadas com sucesso!");
                }

                //controlar situação da capota
                boolean situacaoCapota = panther.abrirFecharCapota();
                if(situacaoCapota){
                    System.out.print("Capota aberta com sucesso!");
                }else{
                    System.out.print("Capota fechada com sucesso!");
                }
                System.out.println();
            }
        }
    }
}