/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        BuscaBinaria classUnderTest = new BuscaBinaria();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
